// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1QSUu5wzv0xDtgdhBHijHzvySbMvk8Ec',
    appId: '1:825913504105:web:81644d45344b29fe714df8',
    messagingSenderId: '825913504105',
    projectId: 'myapp-ae6ae',
    authDomain: 'myapp-ae6ae.firebaseapp.com',
    storageBucket: 'myapp-ae6ae.firebasestorage.app',
    measurementId: 'G-GXNYBVCBSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTFsHthEWVtwIi8egRYVPcJm-tgr8G-WU',
    appId: '1:825913504105:android:3b4336e05fb61314714df8',
    messagingSenderId: '825913504105',
    projectId: 'myapp-ae6ae',
    storageBucket: 'myapp-ae6ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVT674-rXrp9kvhwQ_G7737Gki2G5UklM',
    appId: '1:825913504105:ios:c205d5d02fb987e8714df8',
    messagingSenderId: '825913504105',
    projectId: 'myapp-ae6ae',
    storageBucket: 'myapp-ae6ae.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVT674-rXrp9kvhwQ_G7737Gki2G5UklM',
    appId: '1:825913504105:ios:c205d5d02fb987e8714df8',
    messagingSenderId: '825913504105',
    projectId: 'myapp-ae6ae',
    storageBucket: 'myapp-ae6ae.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1QSUu5wzv0xDtgdhBHijHzvySbMvk8Ec',
    appId: '1:825913504105:web:dd304550d17914ae714df8',
    messagingSenderId: '825913504105',
    projectId: 'myapp-ae6ae',
    authDomain: 'myapp-ae6ae.firebaseapp.com',
    storageBucket: 'myapp-ae6ae.firebasestorage.app',
    measurementId: 'G-HPF6C9W93H',
  );
}
